name: ci

on:
  push:
    branches:
      - "*"

env:
  NODE_VERSION: 20
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_URI_TEST: redis://localhost:6379
  MONGO_URI_TEST: mongodb://localhost:42069/testdb

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # remove frontend, backend/question-service for now
        service: [backend/user-service]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm install

      - name: Linting
        working-directory: ${{ matrix.service }}
        run: npm run lint

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-replica-set: test-rs
          mongodb-port: 42069

      - name: Tests
        working-directory: ${{ matrix.service }}
        run: npm test
